language: python # set desired language

dist: trusty

addons:
  apt:
    sources:
      - google-chrome # if your project contains tests need to be run on chrome include these lines
    packages:
      - google-chrome-stable

addons:
   firefox: "57.0.2" # if your project contains tests need to be run on firefox include these lines


before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024" # running virtual display on desired port with desired settings
  - sleep 3

script:
  # perform build and run commands here
  - sudo apt-get install python-minimal python2.7-dev git gcc libyaml-dev libjpeg-dev libz-dev
  - python bootstrap.py
  - yes
  - bin/buildout -N  
  - bin/buildout -N
  - bin/buildout -N 
  - bin/op_tests -s 1_openProcedure -As_arguments/openeu_testing.txt -v  broker:PrivatMarket -v role:viewer -v api_version:2.4 || true robot_test
  - ls
  - cd bin
  - ls
