language: python # set desired language
virtualenv:
  system_site_packages: true
  
addons:
  apt:
    sources:
      - google-chrome # if your project contains tests need to be run on chrome include these lines
    packages:
      - google-chrome-stable

script:
  # perform build and run commands here
  - sudo apt-get install python-minimal python2.7-dev git gcc libyaml-dev libjpeg-dev libz-dev
  - python bootstrap.py
  - pip uninstall zc.buildout 2.10.0 
  - pip uninstall setuptools 38.2.4 | yes
  - yes
  - bin/buildout -N  
  - bin/buildout -N
  - bin/buildout -N
  - bin/op_tests -s 1_openProcedure -As_arguments/openeu_testing.txt -v  broker:PrivatMarket -v role:viewer -v api_version:2.4 || true robot_test
  - ls
  - cd bin
  - ls
