language: python # set desired language

dist: trusty

system_site_packages: false

python:
 - "2.7"

install:
  - sudo apt-get install python-minimal python2.7-dev git gcc libyaml-dev libjpeg-dev libz-dev

script:
  # perform build and run commands here
  - python bootstrap.py
  - cd /home/travis/build/schvets/robot_tests/eggs
  - ls
  - sudo rm -rf zc.buildout-2.10.0-py2.7.egg
  - ls
  - cd ..
  - python bootstrap.py
  - cd /home/travis/build/schvets/robot_tests/develop-eggs
  - ls
  - cd ..
  - bin/buildout -N
  - cd /home/travis/build/schvets/robot_tests/eggs/
  - sudo rm -rf zc.buildout-2.10.0-py2.7.egg
  - cd ..
  - bin/buildout -N
  - cd /home/travis/build/schvets/robot_tests/eggs/
  - sudo rm -rf zc.buildout-2.10.0-py2.7.egg
  - cd ..
  - bin/op_tests -s 1_openProcedure -As_arguments/openeu_testing.txt -v  broker:PrivatMarket -v role:viewer -v api_version:2.4 || true  - ls
