language: python # set desired language

dist: trusty

system_site_packages: false

python:
 - "2.7"

install:
  - sudo apt-get install python-minimal python2.7-dev git gcc libyaml-dev libjpeg-dev libz-dev

script:
  # perform build and run commands here
  - python bootstrap.py
  - python bootstrap.py
  - bin/buildout -N
  - bin/buildout -N
  - bin/op_tests -s 1_openProcedure -As_arguments/openeu_testing.txt -v  broker:PrivatMarket -v role:viewer -v api_version:2.4 || true  - ls